version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_appa
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "9000:9000"

  webserver:
    image: nginx:alpine
    container_name: nginxa
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysqla
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: aloga
      MYSQL_DATABASE: aloga_cofee
      MYSQL_PASSWORD: cofee
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel:

volumes:
  dbdata:
